name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            set -e
            cd /var/www/shop

            echo '📥 Pulling code...'
            git pull origin main

            echo '🐳 Rebuild containers...'
            docker compose down
            docker compose up -d --build

            sleep 25

            echo '🚀 Running deployment commands...'

            # Все команды последовательно
            docker compose exec -T app composer install --no-dev --optimize-autoloader --no-interaction
            docker compose exec -T app php artisan key:generate --force
            docker compose exec -T app php artisan migrate --force
            docker compose exec -T app php artisan db:seed --force
            docker compose exec -T app npm install --production --silent
            docker compose exec -T app npm run build
            docker compose exec -T app php artisan config:clear
            docker compose exec -T app php artisan cache:clear
            docker compose exec -T app php artisan view:clear
            docker compose exec -T app php artisan route:clear
            docker compose exec -T app php artisan config:cache
            docker compose exec -T app php artisan route:cache
            docker compose exec -T app php artisan view:cache

            echo '✅ Deploy finished!'
          "
